name: movie_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  bloc_test: ^9.0.3
  cached_network_image: ^3.2.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.0.1
  equatable: ^2.0.7
  dartz: ^0.10.0
  dio: ^5.7.0
  http: ^0.13.4
  sqflite: ^2.0.2
  bloc: ^8.1.4
  flutter_modular: ^5.0.3
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^2.0.9
  get_it: ^8.0.2
  google_fonts: ^4.0.4
  hive: ^2.0.5
  http_mock_adapter: ^0.6.1
  intl: ^0.19.0
  mocktail: ^1.0.4
  modular_test: ^2.0.0
  path_provider: ^2.0.8
  pedantic: ^1.11.1
  slidy: ^4.0.4
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true

